# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 162002783+Premkumar1845@users.noreply.github.com
author_name: Prem Kumar Kuppili
preset_name: starter
project_name: Kortexflow-frontend

